spring:
  application:
    name: CONFIG-SERVER-GIT
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8762/eureka    
  instance:
    prefer-ip-address: true
     
